version: '3'
services:
  amazon-classifier:
    image: amazon-classifier
    container_name: amazon-classifier
    volumes:
      - ./:/opt/amazon-classifier
    command: tail -f /dev/null
    ports:
        - "8000:8000"
